stages:
  - build
  - publish


validate-and-prepare:
  image: python
  stage: build
  interruptible: true
  rules:
    - if: $CI_PIPELINE_TRIGGERED
  script:
    - ./validate-and-prepare.py
  artifacts:
    paths:
      - "tools/chocolateyinstall.ps1"
      - "rednotebook.nuspec"

pack-and-push:
  image: chocolatey/choco
  stage: publish
  dependencies:
    - validate-and-prepare
  interruptible: true
  rules:
    - if: $CI_PIPELINE_TRIGGERED
  script:
    - ./pack-and-push.sh
  artifacts:
    paths:
      - "*.nupkg"
